DROP DATABASE IF EXISTS ELECTIONMACHINE;

CREATE DATABASE ELECTIONMACHINE;

ALTER DATABASE ELECTIONMACHINE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ELECTIONMACHINE;

DROP TABLE IF EXISTS CANDIDATES;

DROP TABLE IF EXISTS QUESTIONS;

DROP TABLE IF EXISTS ANSWERS;

CREATE TABLE CANDIDATES (
   CANDIDATE_ID INTEGER NOT NULL,
   FIRST_NAME VARCHAR(30),
   LAST_NAME VARCHAR(30),
   PARTY VARCHAR(60),
   MUNICIPALITY VARCHAR(50),
   AGE INTEGER,
   DESCRIPTION VARCHAR(4000),
   PRIMARY KEY (CANDIDATE_ID));

CREATE TABLE QUESTIONS (
   QUESTION_ID INTEGER NOT NULL,
   QUESTION VARCHAR(200),
   PRIMARY KEY (QUESTION_ID));

CREATE TABLE ANSWERS (
   CANDIDATE_ID INTEGER NOT NULL,
   QUESTION_ID INTEGER NOT NULL,
   ANSWER INTEGER,
   PRIMARY KEY (CANDIDATE_ID, QUESTION_ID));